### ISSUE TITLE
Incorrect AUDBTC counter value

### ISSUE THREAD

**Issue by JacqualineChamber** [LedgerHQ/ledger-live-mobile#1154] opened 2020-02-19 07:32 UTC
#### Expected behaviour 

Correct BTCAUD value is retrieved

#### Actual behaviour

Incorrect BTCAUD value is retrieved

Please don’t use acx.io they are a scam exchange I’m Australia and they do not have the correct BTC value. Consider using values from independent reserve or BTC markets

**Comment by cthepot-ledger** [comment] 2020-10-13 10:36
Duplicate of #1137 will be fixed with new countervalue system we will be introducing shortly

**Closed by cthepot-ledger** 2020-10-13 10:36 UTC
